CREATE USER axiom IDENTIFIED BY Axiom123;
GRANT CONNECT, RESOURCE TO axiom;
GRANT UNLIMITED TABLESPACE TO axiom;


CREATE TABLE SA_DELIVERY_TERMS (
  CODE         NUMBER(3)    NOT NULL,
  S_NAME       VARCHAR2(60) NOT NULL,  -- Arabic name
  B_NAME       VARCHAR2(60) NOT NULL,  -- English name
  DAYS         NUMBER(4),              -- delivery lead time in days
  ACTIVE_FLAG  NUMBER(1)    DEFAULT 1,
  ENTRY_USER   NUMBER(10)   NOT NULL,
  ENTRY_DATE   DATE         NOT NULL,
  CHANGE_USER  NUMBER(10),
  CHANGE_DATE  DATE,
  CONSTRAINT SA_DELIVERY_TERMS_PK PRIMARY KEY (CODE)
);

SELECT * FROM SA_DELIVERY_TERMS;